#!/usr/bin/env python3
"""Download the webfonts used by the popup and options pages into fonts/.

DeMarkup ships its fonts rather than loading them from Google's CDN, so the
extension makes no network requests at runtime. Re-run this only when the font
families or weights in popup.css / options.css change.

Writes three things into fonts/:
  *.woff2         the font files themselves
  font-face.css   the @font-face rules, linked from popup.html and options.html
  LICENSE.md      the OFL text for each family, which must ship alongside the
                  fonts whenever the extension is redistributed
"""

import os
import re
import sys
import urllib.request

CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=DM+Sans:wght@400;500;600"
    "&family=Instrument+Serif"
    "&display=swap"
)

# Chrome UA so Google serves woff2 rather than older formats.
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
)

WANTED_SUBSETS = {"latin", "latin-ext"}

# Both families are under the SIL Open Font License, which requires the licence
# to travel with the fonts. Keyed by family name as Google Fonts reports it.
LICENSES = {
    "DM Sans": "https://raw.githubusercontent.com/google/fonts/main/ofl/dmsans/OFL.txt",
    "Instrument Serif": "https://raw.githubusercontent.com/google/fonts/main/ofl/instrumentserif/OFL.txt",
}

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTS_DIR = os.path.join(PROJECT_DIR, "fonts")


def get(url):
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def parse_faces(css):
    """Yield one dict per @font-face block, tagged with its subset comment."""
    subset = None
    for chunk in re.split(r"(/\*[^*]*\*/)", css):
        comment = re.fullmatch(r"/\*\s*([\w-]+)\s*\*/", chunk.strip())
        if comment:
            subset = comment.group(1)
            continue
        for block in re.findall(r"@font-face\s*\{[^}]*\}", chunk):
            family = re.search(r"font-family:\s*'([^']+)'", block)
            weight = re.search(r"font-weight:\s*(\d+)", block)
            style = re.search(r"font-style:\s*(\w+)", block)
            url = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            unicode_range = re.search(r"unicode-range:\s*([^;]+);", block)
            if not (family and url):
                continue
            yield {
                "subset": subset,
                "family": family.group(1),
                "weight": weight.group(1) if weight else "400",
                "style": style.group(1) if style else "normal",
                "url": url.group(1),
                "unicode_range": unicode_range.group(1).strip() if unicode_range else None,
            }


def main():
    print(f"Fetching {CSS_URL}")
    css = get(CSS_URL).decode("utf-8")

    faces = [f for f in parse_faces(css) if f["subset"] in WANTED_SUBSETS]
    if not faces:
        sys.exit("No matching @font-face blocks found — Google may have changed the format.")

    os.makedirs(FONTS_DIR, exist_ok=True)

    blocks = []
    total = 0
    for face in faces:
        slug = face["family"].replace(" ", "")
        name = f"{slug}-{face['weight']}-{face['subset']}.woff2"
        path = os.path.join(FONTS_DIR, name)

        data = get(face["url"])
        with open(path, "wb") as handle:
            handle.write(data)
        total += len(data)
        print(f"  {name}  ({len(data) / 1024:.1f} KB)")

        lines = [
            "@font-face {",
            f"  font-family: '{face['family']}';",
            f"  font-style: {face['style']};",
            f"  font-weight: {face['weight']};",
            "  font-display: swap;",
            f"  src: url('./{name}') format('woff2');",
        ]
        if face["unicode_range"]:
            lines.append(f"  unicode-range: {face['unicode_range']};")
        lines.append("}")
        blocks.append("\n".join(lines))

    header = (
        "/* Generated by scripts/vendor-fonts.py — do not edit by hand.\n"
        "   Fonts are bundled rather than loaded from a CDN so that DeMarkup\n"
        "   makes no network requests at runtime.\n"
        "   Source: Google Fonts. Licence: SIL Open Font License — see LICENSE.md. */\n"
    )
    css_out = os.path.join(FONTS_DIR, "font-face.css")
    with open(css_out, "w") as handle:
        handle.write(header + "\n" + "\n\n".join(blocks) + "\n")

    families = sorted({f["family"] for f in faces})
    sections = [
        "# Font Licences",
        "",
        "The fonts in this directory are redistributed as part of the DeMarkup",
        "extension. They are not covered by DeMarkup's MIT licence; each family",
        "carries its own SIL Open Font License, reproduced in full below.",
        "",
    ]
    for family in families:
        url = LICENSES.get(family)
        if not url:
            print(f"  WARNING: no licence URL configured for {family}", file=sys.stderr)
            continue
        text = get(url).decode("utf-8").strip()
        sections += [f"## {family}", "", f"Source: {url}", "", "```", text, "```", ""]
        print(f"  licence for {family}  ({len(text) / 1024:.1f} KB)")

    license_out = os.path.join(FONTS_DIR, "LICENSE.md")
    with open(license_out, "w") as handle:
        handle.write("\n".join(sections))

    print(f"\n{len(faces)} font files, {total / 1024:.1f} KB total, in fonts/")
    print(f"@font-face block written to {css_out}")
    print(f"licences written to {license_out}")


if __name__ == "__main__":
    main()
